language: python

matrix:
  include:
    - python: 2.7
      env:
        - COVERAGE=false
        - ARGS=""
    - python: 3.4
      env:
        - COVERAGE=false
        - ARGS=""
    - python: 3.5
      env:
        - COVERAGE=false
        - ARGS=""
    - python: 3.6
      env:
        - COVERAGE=true
        - ARGS="--strict"

before_install:
  - sudo apt-get update -yq
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
  - conda install --yes nomkl

install:
  - conda create --yes --channel=conda-forge --name=test python=$TRAVIS_PYTHON_VERSION nomkl gridgen numpy matplotlib pyproj pytest pytest-cov pytest-pep8 coverage docopt requests pyyaml
  - source activate test
  - pip install codecov
  - pip install -e .

script:
  - coverage run --source pygridgen check_pygridgen.py ${ARGS}

after_success:
  - if [ ${COVERAGE} = true ]; then
      coverage report -m;
      coveralls;
    fi
